In [67]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [68]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [69]:
df = pd.read_csv("loan_approval_dataset.csv")
df.head()

,loan_id,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,1,2,Graduate,No,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved
1,2,0,Not Graduate,Yes,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected
2,3,3,Graduate,No,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected
3,4,3,Graduate,No,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected
4,5,5,Not Graduate,Yes,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected

In [70]:
df.columns = df.columns.str.strip()

In [71]:
encoder = LabelEncoder()
df['education'] = encoder.fit_transform(df['education'])
df['self_employed'] = encoder.fit_transform(df['self_employed'])

In [72]:
df

,loan_id,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,1,2,0,0,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved
1,2,0,1,1,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected
2,3,3,0,0,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected
3,4,3,0,0,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected
4,5,5,1,1,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4264,4265,5,0,1,1000000,2300000,12,317,2800000,500000,3300000,800000,Rejected
4265,4266,0,1,1,3300000,11300000,20,559,4200000,2900000,11000000,1900000,Approved
4266,4267,2,1,0,6500000,23900000,18,457,1200000,12400000,18100000,7300000,Rejected
4267,4268,1,1,0,4100000,12800000,8,780,8200000,700000,14100000,5800000,Approved
4268,4269,1,0,0,9200000,29700000,10,607,17800000,11800000,35700000,12000000,Approved

In [73]:
X = df.drop(columns=['loan_id','loan_status'])
y = df['loan_status']

In [74]:
df

,loan_id,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,1,2,0,0,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved
1,2,0,1,1,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected
2,3,3,0,0,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected
3,4,3,0,0,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected
4,5,5,1,1,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4264,4265,5,0,1,1000000,2300000,12,317,2800000,500000,3300000,800000,Rejected
4265,4266,0,1,1,3300000,11300000,20,559,4200000,2900000,11000000,1900000,Approved
4266,4267,2,1,0,6500000,23900000,18,457,1200000,12400000,18100000,7300000,Rejected
4267,4268,1,1,0,4100000,12800000,8,780,8200000,700000,14100000,5800000,Approved
4268,4269,1,0,0,9200000,29700000,10,607,17800000,11800000,35700000,12000000,Approved

In [75]:
y

0        Approved
1        Rejected
2        Rejected
3        Rejected
4        Rejected
          ...
4264     Rejected
4265     Approved
4266     Rejected
4267     Approved
4268     Approved
Name: loan_status, Length: 4269, dtype: object

In [76]:
X

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value
0,2,0,0,9600000,29900000,12,778,2400000,17600000,22700000,8000000
1,0,1,1,4100000,12200000,8,417,2700000,2200000,8800000,3300000
2,3,0,0,9100000,29700000,20,506,7100000,4500000,33300000,12800000
3,3,0,0,8200000,30700000,8,467,18200000,3300000,23300000,7900000
4,5,1,1,9800000,24200000,20,382,12400000,8200000,29400000,5000000
...,...,...,...,...,...,...,...,...,...,...,...
4264,5,0,1,1000000,2300000,12,317,2800000,500000,3300000,800000
4265,0,1,1,3300000,11300000,20,559,4200000,2900000,11000000,1900000
4266,2,1,0,6500000,23900000,18,457,1200000,12400000,18100000,7300000
4267,1,1,0,4100000,12800000,8,780,8200000,700000,14100000,5800000
4268,1,0,0,9200000,29700000,10,607,17800000,11800000,35700000,12000000

In [77]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=101)

In [78]:
from sklearn.metrics import accuracy_score, classification_report

In [79]:
model = DecisionTreeClassifier(max_depth=5, random_state=101)

In [80]:
model.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=5, random_state=101)

In [81]:
y_pred = model.predict(X_test)

In [82]:
accuracy = accuracy_score(y_test , y_pred)
print(f"Accuracy of the model {model} : {accuracy:.2f}")

Accuracy of the model DecisionTreeClassifier(max_depth=5, random_state=101) : 0.97

In [83]:
import joblib

In [88]:
joblib.dump(model , "decision_tree.pkl")

['decision_tree.pkl']

In [85]:
loaded_model = joblib.load('decision_tree.pkl')

In [86]:
loaded_model.predict(X_test)

array([' Rejected', ' Rejected', ' Approved', ..., ' Rejected',
       ' Rejected', ' Approved'], shape=(1068,), dtype=object)